modLoader="javafml"
loaderVersion="[47,)"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
description='''
${mod_description}
'''
authors="${mod_authors}"

# APIは前提にされる側なので依存は基本なし
